# Generated by Django 5.1.6 on 2025-02-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('active', '发布'), ('draft', '草稿')], default='active', max_length=10),
        ),
    ]
